CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    user_image_url VARCHAR(3000) NOT NULL,
    description TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS posts (
    postid BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
    userid BIGSERIAL NOT NULL,
    post_text TEXT NOT NULL
);